//
// Created by user on 28.08.22.
//

#ifndef HARDWARECONTROL2_CALIBRATION_H
#define HARDWARECONTROL2_CALIBRATION_H

#define DAC1_MINIMUM_VALUE 40
#define DAC2_MINIMUM_VALUE 40

#endif //HARDWARECONTROL2_CALIBRATION_H
